name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  build:
    runs-on: ubuntu-latest
    needs: clone
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t my-org/my-app:${{ github.sha }} .

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        python-version: [3.8, 3.11]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install pytest

      - name: Run tests
        run: pytest tests/

  security:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: my-org/my-app:${{ github.sha }}

      - name: Run OWASP Dependency-Check
        uses: dependency-check/scan-action@v2
        with:
          project: my-app
          scan: .

  deploy:
    runs-on: ubuntu-latest
    needs: [test, security]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy App
        env:
          ENVIRONMENT: production
          DEPLOY_SECRET: ${{ secrets.DEPLOY_SECRET }}
        run: |
          echo "Deploying to $ENVIRONMENT"

  notify:
    runs-on: ubuntu-latest
    needs: deploy
    if: failure()
    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "Deployment failed for my-org/my-app on branch ${{ github.ref_name }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}